language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mkkos123/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkkos123/client-test npm test

after_success:
  - docker build -t mkkos123/multi-client ./client
  - docker build -t mkkos123/multi-nginx ./nginx
  - docker build -t mkkos123/multi-server ./server
  - docker build -t mkkos123/multi-worker ./worker

  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker-hub
  - docker push mkkos123/multi-client
  - docker push mkkos123/multi-nginx
  - docker push mkkos123/multi-server
  - docker push mkkos123/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-north-1-085471374027
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
